#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

FILE="/proc/net/dev"
#FILE="/proc/net/if_inet6"

if [ -f $FILE ] && [ "$(grep tun $FILE)" ]; then
    #echo ""		# short text
    echo ""		# short text
    echo "VPN: up"	# full text
    echo "#55F055"
else
    echo ""		# short text
    echo "VPN: down"	# full text
    echo "#F05555"
fi

#------------------------------------------------------------------------

